### ISSUE TITLE
python config_vars.py    error

### ISSUE THREAD

**Issue by gaowudao** [giswqs/geemap-heroku#1]
I followed the steps to run the example. When excute the python config_vars.py, the error occured as follow:

Command '['heroku', 'config:set', 'EARTHENGINE_TOKEN="******]' returned non-zero exit status 1.

**Comment by giswqs** [comment]
Do NOT post your Earth Engine token publicly!! This is a huge security risk. Anyone can use your token to access your GEE account. If the script does not work for you, you can retrieve the token from your computer and define it on your heroku app. 

https://dashboard.heroku.com/apps

![](https://i.imgur.com/3XzjP6C.png)
![](https://i.imgur.com/t74ZXji.png)

**Comment by gaowudao** [comment]
wow, Thank you very much and your suggestion. I will try.

**Comment by Ojaybee** [comment]
This line in config_vars.py is throwing an error for me:
`check_call(['heroku', 'config:set', secret], stdout=DEVNULL, stderr=STDOUT)`

I'm on windows 10 and the error message is:
`[WinError 2] The system cannot find the file specified`

Checking the 'token' the slice is incorrect for the windows file. It should be:
`token = content.split(':')[1][2:-2]`
to include all characters excluding double quotation marks. Despite this the above error still persists.

**Comment by Ojaybee** [comment]
Full working code for Windows 10:

```
import os
from subprocess import DEVNULL, STDOUT, check_call

def set_heroku_vars(token_name='EARTHENGINE_TOKEN'):
    """Extracts Earth Engine token from the local computer and sets it as an environment variable on heroku.

    Args:
        token_name (str, optional): Name of the Earth Engine token. Defaults to 'EARTHENGINE_TOKEN'.
    """
    try:

        ee_token_dir = os.path.expanduser("~/.config/earthengine/")
        ee_token_file = os.path.join(ee_token_dir, 'credentials')

        if not os.path.exists(ee_token_file):
            print('The credentials file does not exist.')
        else:
            with open(ee_token_file) as f:
                content = f.read()
                token = content.split(':')[1][2:-2]
                secret = '{}={}'.format(token_name, token)
                check_call(['heroku', 'config:set', secret], stdout=DEVNULL, stderr=STDOUT, shell=True)

    except Exception as e:
        print(e)
        return

if __name__ == '__main__':

    set_heroku_vars(token_name='EARTHENGINE_TOKEN')
```

**Comment by giswqs** [comment]
@Ojaybee Thank you very much for taking the time to debug the code and provide a working example. I did not realize that the credentials file on Linux is different from the one on Windows/macOS, which has an extra space in it. Therefore, the token slicing on Linux should be different from Windows/macOS. I have incorporated your solution and the config file now seems to run successfully on both Linux and Windows. Thanks.

**Comment by giswqs** [comment]
Use the following in your notebook before doing anything with ee. Otherwise, the authentication will fail.

import geemap
Map = geemap.Map()

**Comment by vijaygrg27** [comment]
I am trying your examples. I have committed your code in my repo  but I am not able to deploy it through my github repo. I have deployed the examples with your repo.  It's giving problem in my repo
my repo https://myfarm12.herokuapp.com/ is not working 
your repo https://powerful-retreat-90626.herokuapp.com/ is wroking fine

**Comment by giswqs** [comment]
That mean your EE token was not set properly. Login to heroku to set the token manually. See https://github.com/giswqs/geemap-heroku/issues/1#issuecomment-656101951

**Comment by vijaygrg27** [comment]
I am able to do so .It's working fine.I want to update my live location on map.Can you please provide me any source code for Geemap.

**Comment by giswqs** [comment]
What do you mean by 'live location'?

**Comment by vijaygrg27** [comment]
I want to update the live location on map like Google maps.

**Comment by giswqs** [comment]
I just implemented this feature. Update the package using `geemap.update_package()` and then use the following example to zoom to the map to the current device location.

```
import geemap
Map = geemap.Map()
Map.zoom_to_me(zoom=14, add_marker=True)
Map
```

**Comment by vijaygrg27** [comment]
Thanks I will check and get back to you

**Comment by vijaygrg27** [comment]
Location is not correct. I also want track my location like Google map

**Comment by giswqs** [comment]
Try the example below. If it does not give you the correct location, then it is the problem of [geocoder](https://github.com/DenisCarriere/geocoder), not geemap. 

```
import geocoder

g = geocoder.ip("me")
props = g.geojson["features"][0]["properties"]
lat = props["lat"]
lon = props["lng"]
print(lat, lon)
```

**Comment by vijaygrg27** [comment]
https://openlayers.org/workshop/en/mobile/compass.html 
Please check this documentation

**Comment by vijaygrg27** [comment]
I will try to run this code on mobile.  I think It's not working due to laptop.

**Comment by giswqs** [comment]
geemap is not designed for mobile use. It is not a GPS application. It does not use OpenLayers. geemap will not support getting live locations.

**Comment by vijaygrg27** [comment]
How can do it? I am making my project using your Geemap library only. Please guide me

**Comment by vijaygrg27** [comment]
I have done everything but my last part is to update the live location on map

**Comment by giswqs** [comment]
I already told you. geemap does not support getting live locations. Period.

**Comment by vijaygrg27** [comment]
Ok 😔

**Comment by vijaygrg27** [comment]
Can you please tell me how to calculate the NDVI using planetscope imagery?
I want to draw NDVI time series from planet scope imagery.
