### ISSUE TITLE
I have added the key in Heroku config_vars but I am getting this error. When run by jupyter voila it's working

### ISSUE THREAD

**Issue by sumitsaini326** [giswqs/geemap-heroku#13]
Earth Engine App
To authorize access needed by Earth Engine, open the following URL in a web browser and follow the instructions:

https://code.earthengine.google.com/client-auth?scopes=https%3A//www.googleapis.com/auth/earthengine%20https%3A//www.googleapis.com/auth/devstorage.full_control&request_id=9VJRWiemEVkPLY2h550_HkB5-JyKRjH86je8n038p-A&tc=xTMdt__slBkZHi7NZYGSw_r4wPmZQhpaOLlKDecjeOM&cc=JIpYkgp4F048wbW_nP7lmWABhN25filj4By0uBXG08E

The authorization workflow will generate a code, which you should paste in the box below

There was an error when executing cell [2]. Please run Voilà with --show_tracebacks=True or --debug to see the error message, or configure VoilaConfiguration.show_tracebacks.

**Comment by giswqs** [comment]
Try rebooting the app and update geemap to the latest version

**Comment by sumitsaini326** [comment]
I tried this but still same error. I also updated refresh_token "config\earthengine\credentials"

**Comment by sumitsaini326** [comment]
**i am using this code with  ee.Initialize()**
![image](https://user-images.githubusercontent.com/39621731/165891665-2121a9f5-0a2b-422e-8ec0-f5959d6af883.png)

**i am using this code without  ee.Initialize()**
![image](https://user-images.githubusercontent.com/39621731/165892059-ce67db29-81cb-4b76-84c7-c47fa4cc14b6.png)


**I have update earth engine  token** 
![image](https://user-images.githubusercontent.com/39621731/165891934-537f2c2d-8ee7-4571-8aa2-4e429d282009.png)


**both are code getting this error. i have also changed google account**

To authorize access needed by Earth Engine, open the following URL in a web browser and follow the instructions:
https://code.earthengine.google.com/client-auth?scopes=https%3A//www.googleapis.com/auth/earthengine%20https%3A//www.googleapis.com/auth/devstorage.full_control&request_id=igRnV4OAr6p_vgmgsW-OdUwrtuFggA5S0nu--vvxTSQ&tc=48naltTLYNL7ExLamtlkExhwWam8mWWe6xabF_612rA&cc=qfpvBigm6-ac5PkftI2SiYE7KsCGGEdqmMEuM9TDr28

The authorization workflow will generate a code, which you should paste in the box below

There was an error when executing cell [2]. Please run Voilà with --show_tracebacks=True or --debug to see the error message, or configure VoilaConfiguration.show_tracebacks.

**Comment by saravanaganesh18** [comment]
@sumitsaini326 Hi, did you fix the issue. I am facing the same Authorization - viola issue.

Could you tell me how to run the app using viola ?

**Comment by saravanaganesh18** [comment]
Hi @giswqs 

Things i have done

1) Authenticated earthengine from cmd prompt
![image](https://user-images.githubusercontent.com/37054331/167284783-042824c5-0ad9-4ee1-b388-b243dc80d12a.png)

2) Copied the authorization key from the saved credentials json file to Heroku
![image](https://user-images.githubusercontent.com/37054331/167284810-b6e24b58-6729-4a65-8b3c-549cea321d28.png)

3) Even then, i am getting the same error
![image](https://user-images.githubusercontent.com/37054331/167284829-949be8df-4a75-477a-935a-e5d717de6178.png)

**Comment by neko1010** [comment]
Same issue for me - worked locally, but not hosted. I updated geemap, which downgraded shapely, and now am receiving a new error when trying to view locally:  `ImportError: cannot import name 'StaticModule' from 'setuptools.config' (/usr/lib/python3/dist-packages/setuptools/config.py)`. With both `heroku local web` and `voila <notebook> --show_tracebacks=TRUE`. Any help greatly appreciated.

**Comment by giswqs** [comment]
What Python version are you using?

**Comment by giswqs** [comment]
@neko1010 I meant to ask what Python you are using on Heroku? Not the Python version on your local computer.

**Comment by giswqs** [comment]
I just deployed the app from the repo. It works just fine. Please clone this repo and and deploy the app without making any changes. Make sure you set the `EARTHENGINE_TOKEN` as an environment variable. Once the app deployed successfully, then you can start adding your own notebooks to the app. 

https://geemap-demo.herokuapp.com

![image](https://user-images.githubusercontent.com/5016453/167748126-c057b3d1-ea66-49db-b0da-cb21ffba4d9b.png)

**Comment by mandeeptimalsina** [comment]
![Screenshot (422)](https://user-images.githubusercontent.com/96986350/169529164-59dd16d9-1e92-421f-9aaf-4bc4f94cdac8.png)

I too have same google earth authentication isuue I have done same as said and I haven't changed my notebook(used as in repo for testing).And I have above error.
I add voila.json file with 
`{
  "VoilaConfiguration": {
    "show_tracebacks": true
  }
}`
then voila error was removed but the following error showed up . 
![Screenshot (423)](https://user-images.githubusercontent.com/96986350/169533641-fe47143d-7831-4f85-87e0-104c99380116.png)
![Screenshot (424)](https://user-images.githubusercontent.com/96986350/169533650-cfea801a-db6e-422e-912b-63077376be2c.png)
![Screenshot (425)](https://user-images.githubusercontent.com/96986350/169533653-5ce0d959-826a-4f05-afb4-c8061ef859a8.png)
![Screenshot (426)](https://user-images.githubusercontent.com/96986350/169533657-e093c06c-d39f-43e6-ba4c-de9adc54465d.png)

I things something should be changed in config_vars as the way of authenticating google earth engine has been changed by google.

**Comment by giswqs** [comment]
@mandeeptimalsina You can set the `EARTHENGINE_TOKEN` on the Heroku settings. You don't have to use config_vars.

https://dashboard.heroku.com/apps/geemap/settings
![image](https://user-images.githubusercontent.com/5016453/169673885-afc90a2f-cb6d-474d-a5f9-89865ecbab50.png)
