### ISSUE TITLE
trouble opening app on web and locally

### ISSUE THREAD

**Issue by neko1010** [giswqs/geemap-heroku#14]
![image](https://user-images.githubusercontent.com/28967975/167910518-6928d077-fb38-4751-bb95-a161b7fd3d31.png)
I have again cloned the repo and receive the above error message when trying to view the water-app. When I try to open the app locally with `heroku local web` i receive this error message: `ImportError: cannot import name 'StaticModule' from 'setuptools.config' (/usr/lib/python3/dist-packages/setuptools/config.py)`. I followed the instructions for adding the EE token to Config Vars on the heroku website. What am I missing?

**Comment by neko1010** [comment]
I am sure you are right. I can open your link no problem. What is your recommendation? I am on a linux OS

**Comment by giswqs** [comment]
It does not matter what OS you are using locally. If you clone my repo and deploy it to Heroku without making changes, it should work just fine. Don't forget to set the `EARTHENGINE_TOKEN` environment variable.

**Comment by neko1010** [comment]
I updated the `EARTHENGINE_TOKEN` in Heroku - is this correct? 
![image](https://user-images.githubusercontent.com/28967975/167940791-1a7999ec-e88f-4071-9480-d3f142b7f436.png)

**Comment by giswqs** [comment]
See https://github.com/giswqs/geemap-heroku/issues/17
