### ISSUE TITLE
A marker is drawn instead of a circle in Earth Engine App (geemap.ipynb)

### ISSUE THREAD

**Issue by joaoambiente** [giswqs/geemap-heroku#16]
When using the "draw a circle option" here:
https://geemap-demo.herokuapp.com/voila/render/geemap.ipynb?

Only a marker is getting drawn, not a circle.

**Comment by giswqs** [comment]
That's an issue with ipyleaflet. There is not much I can do about it. See https://github.com/jupyter-widgets/ipyleaflet/issues/876
