### ISSUE TITLE
error authentication - solved

### ISSUE THREAD

**Issue by jimmPinedos** [giswqs/geemap-heroku#17]
Hello, I was strugling with the authentication issue, heroku did not regonize. I don't know why the credentials are not being copy well from the code, but I could fix it by coppying the full code id+token and not only the token. I hope it helps somebody with the same issue.

Thank you by the awesome material

![e2](https://user-images.githubusercontent.com/96349726/174199819-77be74b3-0b55-4dd0-aa79-833713a7f70d.jpg)

**Comment by jimmPinedos** [comment]
By the way, it didn't work in python10 that heroku has now, so I create the runtime.text file to specify python3.9.13

**Comment by giswqs** [comment]
Yes, the Earth Engine API Authentication does does not seem to support Python 3.10 yet. It is not a geemap issue.

**Comment by giswqs** [comment]
Closing this issue for now. It has been pinned on top so others should be able see it easily.

**Comment by jimmPinedos** [comment]
Hello again professor. I'm having some issues with the authenticator. More or less every week it "expire" and show me the error to authorize with the key. They way I was temporaly solving was running again in my desktop inserting new code and then pushing the heroku master again. Do you have any idea why this is happening and how to solve it? thank you in advance

**Comment by giswqs** [comment]
No, you don't need to authenticate it every week. Simply copy the **ENTIRE** content of the `credentials` file from your computer and paste it to the Heroku settings.

**Comment by jimmPinedos** [comment]
Thanks for quick answer, I'll show you next time when it appears. I didn't capture the screen this time

**Comment by carbontoolci** [comment]
Hello profession, did the way to set token changed in the latest versions of geemap? I'm having issues when I upload the app into onrender, the "Error Authorize" needed, same issue in Heroku, but it does not happend when I back to geemap==0.19.2

**Comment by jimmPinedos** [comment]
Hello professor, did the way to set token changed in the latest versions of geemap? I'm having issues when I upload the app into onrender, the "Error Authorize" needed, same issue in Heroku, but it does not happend when I back to geemap==0.19.2
