### ISSUE TITLE
Trying onrender.com instead of Heroku

### ISSUE THREAD

**Issue by Spiruel** [giswqs/geemap-heroku#19]
Following Heroku discontinuing its free tier, I have been look at moving my app to another free alternative, such as onrender.com.

I'm using the same repository and setting a secret `EARTHENGINE_TOKEN` properly. Unfortunately I am still encountering authentication problems and I can't work out what I'm missing.

```
RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
```

The app is hosted at https://spen-farm.onrender.com/. (It used to be spen-farm.herokuapp.com).

I am posting here as the procedure is almost identical to the Heroku set-up, and I'm hoping there's a quick solution. Please let me know if there's any other places to host geemap apps for free (I'm having similar auth issues with streamlit).

Thanks

**Comment by giswqs** [comment]
I have not tried out onrender yet. See https://github.com/giswqs/geemap-heroku/issues/17#issuecomment-1182703454 if it helps.

**Comment by Spiruel** [comment]
Unfortunately no success trying out #17.

It seems that I'm having problems authenticating any new geemap app on streamlit, onrender, etc. My issue does not seem to be specific to onrender so it might be something to do with my token in particular. Is there a limit to how many apps I can have for one refresh token?

Problems with both: 

https://spen-farm.streamlit.app/
and
https://spen-farm.onrender.com/

Where streamlit apps with the same EARTHENGINE_TOKEN are working fine, whereas this new deployment is not... (Python 3.9)

**Comment by giswqs** [comment]
Does it work locally?

**Comment by giswqs** [comment]
There is no limit to how many apps you can have, but GEE only allow a few concurrent connections, so you can't use too many apps simultaneously. But should be able to deploy them.

**Comment by Spiruel** [comment]
That's good to know about there being no limits to how many apps you can have, thanks.

Yes I can run my app locally with no issues.

**Comment by Spiruel** [comment]
Hi,

Managed to fix this - it turned out to be a problem related to the kernel defined in the Jupyter notebook. The ee authentication messages that were throwing me off were likely due to the `ee` package and not the `earthengine-api`. After updating the notebook to use the correct environment, it deployed in a similar way to Heroku.

As for those looking for an alternative to heroku for free geemap app hosting - onrender.com does seem to be worth considering.

Thanks

**Comment by jimmPinedos** [comment]
Thanks for this update, it is interesting to know the alternative. Do you know if there is a way to install the app into our own hosting/domain service?
