### ISSUE TITLE
Runtime.txt update

### ISSUE THREAD

**Issue by viniciusgcjr** [giswqs/geemap-heroku#2]
Supported runtimes 
python-3.9.1 on all supported stacks
python-3.8.7 on all supported stacks
python-3.7.9 on all supported stacks
python-3.6.12 on all supported stacks
python-2.7.18 on Heroku-16 and Heroku-18 only

https://devcenter.heroku.com/articles/python-support

**Comment by viniciusgcjr** [comment]
Supported runtimes
python-3.9.1 on all supported stacks
python-3.8.7 on all supported stacks
python-3.7.9 on all supported stacks
python-3.6.12 on all supported stacks
python-2.7.18 on Heroku-16 and Heroku-18 only

https://devcenter.heroku.com/articles/python-support

**Comment by giswqs** [comment]
Runtime has been updated to python 3.8.8
