### ISSUE TITLE
Please authorize access to your Earth Engine account by running  earthengine authenticate

### ISSUE THREAD

**Issue by francofrolla** [giswqs/geemap-heroku#4]
Hi, I haved some problems with the  earthengine authenticate, I used a alternative way:

In the first cell in jupyter notebook: 

    import ee
    import json
    from ee import oauth

    refresh_token =("YOUR API KEY FORM .config/earthengine/credentials")

    from google.oauth2.credentials import Credentials

    clave = Credentials(
        None,
        refresh_token=refresh_token,
        token_uri=oauth.TOKEN_URI,
        client_id=oauth.CLIENT_ID,
        client_secret=oauth.CLIENT_SECRET,
        scopes=oauth.SCOPES)

    ee.Initialize(credentials = clave)

I dont know if a is a secure option, you know? but is work well.

Thanks for geemap, is a awesome!!!

Best regards. 
Franco Frolla

**Comment by giswqs** [comment]
See https://github.com/giswqs/geemap/discussions/465#discussioncomment-710744

**Comment by francofrolla** [comment]
Ok Qiusheng, thanks for all.
