### ISSUE TITLE
NDVI using planetscope imagery by selecting the ROI

### ISSUE THREAD

**Issue by vijaygrg27** [giswqs/geemap-heroku#5]
Hi Dr. Qiusheng Wu.
I have an account of planetscope imagery. Can you please share any resource to calculate NDVI by selecting roi?

**Comment by giswqs** [comment]
- https://developers.google.com/earth-engine/guides/image_math
- https://developers.google.com/earth-engine/guides/image_visualization#clipping

**Comment by vijaygrg27** [comment]
Hi Dr. Qiusheng Wu,

Thanks for the response.
You have already made videos and examples to calculate NDVI on Landsat but I want to calculate NDVI on planetscope imagery.
Planetscope data is not available on google earth engine because it is not free of cost.Should I upload planetscope tiles on google earth engine? 

Can I use these code on planetscope imagery?
