### ISSUE TITLE
Application error issue

### ISSUE THREAD

**Issue by mandeeptimalsina** [giswqs/geemap-heroku#9]
I have done everything as there is in tutorial but the webpage is not loading. I have used the water_app.ipynb as notebook, provided is repo. but application error showed up. I have attached the error logs.
![Screenshot (11)](https://user-images.githubusercontent.com/96986350/147883346-22119efd-efe7-4aa6-b826-54f5906d1d35.png)
![Screenshot (12)](https://user-images.githubusercontent.com/96986350/147883350-a776e027-cec1-4228-96f0-f3bf7ce2cce4.png)

**Comment by giswqs** [comment]
Fork this repo. Don't make any changes, and then deploy it to Heroku. If it works fine, then it is the problem of your own files.

**Comment by mandeeptimalsina** [comment]
I have done as you have said. Still no luck. I need this for my college project. Please help.

**Comment by mandeeptimalsina** [comment]
Adding voila.ip=0.0.0.0 in procfile did the trick for me.
`web: voila --port=$PORT --Voila.ip=0.0.0.0 --no-browser --strip_sources=True --enable_nbextensions=True --MappingKernelManager.cull_interval=60 --MappingKernelManager.cull_idle_timeout=120 notebooks/geemap.ipynb`

**Comment by giswqs** [comment]
Glad to know that you figured it out. I have added the ip option to the repo. Thanks.
